version: '3.9'

services:
  api:
    build:
      context: .
    image: power_systems_data_api_demonstrator:${POWER_SYSTEMS_DATA_API_DEMONSTRATOR_VERSION:-latest}
    restart: always
    ports:
      - 8000:8000
    environment:
      POWER_SYSTEMS_DATA_API_DEMONSTRATOR_HOST: 0.0.0.0
      POWER_SYSTEMS_DATA_API_DEMONSTRATOR_RELOAD: "True"
      POWER_SYSTEMS_DATA_API_DEMONSTRATOR_DB_FILE: /db_data/db.sqlite3
    volumes:
    - power_systems_data_api_demonstrator-db-data:/db_data/

volumes:
  power_systems_data_api_demonstrator-db-data:
    name: power_systems_data_api_demonstrator-db-data
